title: datart
subtitle: "新一代数据可视化开放平台，支持报表、仪表板、大屏、分析和可视化数据应用的敏捷构建"
description: "datart 是新一代数据可视化开放平台，支持各类企业数据可视化场景需求，如创建和使用报表、仪表板和大屏，进行可视化数据分析，构建可视化数据应用等。由原 davinci 主创团队出品，datart 更加开放、可塑和智能，并在数据与艺术之间寻求最佳平衡"
author: datart
language: en
timezone: UTC

url: https://github.com/running-elephant/datart-docs.git
root: /datart-docs/
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0
pretty_urls:
  trailing_index: false
  trailing_html: false

theme: navy

highlight:
  enable: true
  line_number: false

# disqus_shortname: datart
github: running-elephant/datart

deploy:
  type: git
  repo: git@github.com:running-elephant/datart-docs.git
  branch: gh-pages

skip_render: [api/**]